### ISSUE TITLE
dashboard sidebar collapsed = TRUE state not working

### ISSUE THREAD

**Issue by arihanth-jain** [DivadNojnarg/shinydashboardPlus#17]
Hi, setting dashboardSidebar with collapsed to TRUE is not working. The app still starts in default uncollapsed state.

Thanks.

**Comment by DivadNojnarg** [comment]
Could you send a reprex please?

**Comment by DivadNojnarg** [comment]
You need:

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

shinyApp(
  ui = dashboardPagePlus(
    collapse_sidebar = TRUE,
    dashboardHeaderPlus(
      enable_rightsidebar = TRUE,
      rightSidebarIcon = "gears"
    ),
    dashboardSidebar(collapsed = TRUE),
    dashboardBody(),
    rightsidebar = rightSidebar()
  ),
  server = function(input, output) {}
)
```

Especially the collapse_sidebar = TRUE argument in `dashboardPagePlus()`. By the way, you are right that I should remove the collapse argument from dashboardSidebar (comes from shinydashboard). This is a useless overlapping 👍

**Comment by arihanth-jain** [comment]
Sorry for my late response and thanks for your input. It works !
