### ISSUE TITLE
Package not available for download

### ISSUE THREAD

**Issue by kmorrisroe** [DivadNojnarg/shinydashboardPlus#20]
Would love to use this package for the second sidebar but am having issues downloading it.

```
install.packages("shinydashboardPlus")

Warning message:
package 'shinydashboardPlus' is not available (for R version 3.4.2)
```

Also, the example @ [http://130.60.24.205/shinydashboardPlus/](url) breaks somewhere in the code.

**Comment by DivadNojnarg** [comment]
Can you give me the result of `sessionInfo()`please?
I don't see your problem regarding the example:  http://130.60.24.205/shinydashboardPlus/, what happens?

**Comment by serkserk** [comment]
I sometime have the same issue with Rstudio, restarting my VM fix the issue (had the same error this morning when instaling this package)

And the exemple website have a grey filter after 2 secondes, like when there is a error

**Comment by kmorrisroe** [comment]
Looks like my proxy settings were off so it wasn't reaching Cran. No issues with the application, just downloaded it. Sorry for the unnecessary open issue, feel free to close.

And yes, the example turns grey after 2 seconds, a typical feature if the code hit a snag in `Shiny `. May be nothing, but thought I'd let you know.
