### ISSUE TITLE
Can license be GPL v2 or MIT?

### ISSUE THREAD

**Issue by happyshows** [DivadNojnarg/shinydashboardPlus#3]
Hi,

I'd like to use this package in my projects. However, I'm having difficulty to get approval to use it if it's GPL v3.

(I'm unsure about the upstream license dependancies of your package)

Thanks.

**Comment by DivadNojnarg** [comment]
You can use it for sure in your project. Don't worry.

**Comment by happyshows** [comment]
Thanks, would you mind updating that in the description/license file in the next release? It's not urgent, and I just want to make sure when the review team looks at this package, they won't give me any trouble. 

Appreciate it.

**Comment by DivadNojnarg** [comment]
Ok! I will close it for the next release.
