### ISSUE TITLE
How to show a different icon with the collapsed sidebar?

### ISSUE THREAD

**Issue by cecilialee** [DivadNojnarg/shinydashboardPlus#6]
<img width="149" alt="screen shot 2018-07-05 at 6 59 07 pm" src="https://user-images.githubusercontent.com/8072787/42319786-964c0f6e-8085-11e8-8f66-77fbacd0ae6e.png">

Hi! I wonder how can I change the `title` to an icon/image when it's collapsed?

Thanks!

**Comment by DivadNojnarg** [comment]
Hi Cecilia. 
Before going further I noticed an error in the latest CRAN version (in the rightSidbar function, especially when you do not provide any element). Therefore you should install the latest dev version from GitHub.

```r
devtools::install_github("DivadNojnarg/shinydashboardPlus")
```

I assume you would like something like that:
```r
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  
  shinyApp(
    ui = dashboardPagePlus(
      header = dashboardHeaderPlus(
        title = tagList(
          span(class = "logo-lg", "shiny"), 
          img(src = "https://image.flaticon.com/icons/svg/204/204074.svg")),
        enable_rightsidebar = TRUE,
        rightSidebarIcon = "gears"
      ),
      sidebar = dashboardSidebar(),
      body = dashboardBody(),
      rightsidebar = rightSidebar(),
      title = "DashboardPage"
    ),
    server = function(input, output) { }
  )
```

**Comment by cecilialee** [comment]
Amazing! You're awesome Divad!

**Comment by DivadNojnarg** [comment]
In the AdminLTE2 library, they add the class "logo-mini" in the image tag:
```r
img(class = "logo-mini", src = "https://image.flaticon.com/icons/svg/204/204074.svg"))
```
but that's not a big difference

**Comment by yenzichun** [comment]
Hi, Divad

I found this topic about sidebar. So I just comment here...
I am wondering if it is possible to adjust the width of the collapsed sidebar? (default is 50px !important)

I tried to set this in css:
```r
.sidebar-mini.sidebar-collapse .main-sidebar {
    width: 15vw ! important;
}
```
But it doesn't change the width of the top-left icon.
![image](https://user-images.githubusercontent.com/6956697/54006919-5cd8ec80-419a-11e9-970b-472d724579af.png)

Please help me to find a solution or any alternative approach.

**Comment by cttnguyen** [comment]
Is there a way to add a hyperlink to the logo/title combination?

I've tried a few variations on your suggested title option like the following, moving the `a()` around or adding one for each of the `span()` and `img()` functions. The hyperlink works, but the text is no longer replaced by the logo.
```
tagList(
          a(href = "www.google.com/",
             span(class = "logo-lg", "shiny"), 
             img(src = "https://image.flaticon.com/icons/svg/204/204074.svg")
             )
)
```

**Comment by racheldsoh** [comment]
Hi @DivadNojnarg ,
I've tried to change the icon of the rightSidebar by adding the code below (following the example above), but without success.
```
        enable_rightsidebar = TRUE,
        rightSidebarIcon = "info"
```
How can it be done (say changing the icon from `gears` to `info`) in v2.0.1?
Thanks, Rachel

**Comment by DivadNojnarg** [comment]
@racheldsoh : now this is done with the `dashboardHeader` function and `controlbarIcon` parameter. This feature has been aligned with `{bs4Dash}` recently.

**Comment by HugoGit39** [comment]
How does this work in bs4Dash?
